/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/*
    IMPORTANT
    IMPORTANT
    IMPORTANT
this interface im adding after the first draft for more complexity



IMPORTANT
IMPORTANT
*/





package wOutIAmk4;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static wOutIAmk4.ManagerInterface.rList;



/**
 *
 * @author mesaj
 */
public class EditInterface extends javax.swing.JFrame {
    
    public EditInterface() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addExButton = new javax.swing.JButton();
        delExButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        AAAA = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addExButton.setText("Add Exercise");
        addExButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addExButtonActionPerformed(evt);
            }
        });

        delExButton.setText("Delete Exercise");
        delExButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delExButtonActionPerformed(evt);
            }
        });

        closeButton.setText("Close");
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });

        AAAA.setText("wOutDisplay");

        jLabel1.setText("This is a functionality that I'll be adding after the first draft for added complexity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(162, 162, 162))
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(addExButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delExButton)
                .addGap(52, 52, 52))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AAAA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AAAA, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addExButton)
                    .addComponent(delExButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
   
    
    //button action listners
    
    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
 dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void addExButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExButtonActionPerformed
    
        
        
    }//GEN-LAST:event_addExButtonActionPerformed

    private void delExButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delExButtonActionPerformed
          int choice = 0;
          String directions = "What is the position in this routine of the exercise that you want to delete.(you would write 2 for the 2nd exercise)"; 
          choice = Integer.parseInt(JOptionPane.showInputDialog(null, directions, "Delete which Exercise", HEIGHT));
          if(choice < 1){
               JOptionPane.showMessageDialog(null, "Please enter a number greater than zero", "Error", JOptionPane.WARNING_MESSAGE);
               choice = Integer.parseInt(JOptionPane.showInputDialog(null, directions, "Delete which Exercise", HEIGHT));
          }
          int rChoice = choice - 1;
         /* int uni = universal;
          String[] newExercises = new String[(rList.get(uni).getnumExercises()) - 1];
          */
          AAAA.setText(rList.get(rChoice).geteListForEdit());
    }//GEN-LAST:event_delExButtonActionPerformed

    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditInterface().setVisible(true);
             
            }
        });
    }

   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel AAAA;
    private javax.swing.JButton addExButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton delExButton;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
