/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wOutIAmk4;


import javax.swing.JOptionPane;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

/**
 *
 * @author mesaj
 */
public class ManagerInterface extends javax.swing.JFrame {

    
    
    
    /**
     * Creates new form ManagerInterface
     */
    public ManagerInterface() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        viewButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createButton.setText("Create Workouts");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Workouts");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        viewButton.setText("View Workouts");
        viewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Personal Trainer Interface");

        editButton.setText("Edit Workout");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createButton)
                    .addComponent(viewButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createButton)
                    .addComponent(deleteButton))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewButton)
                    .addComponent(editButton))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public static ArrayList<Routine> rList = new ArrayList<Routine>();
    public static int universal;
    
    //button actions
    
    
    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        // TODO add your handling code here:
        String rName = JOptionPane.showInputDialog("What would you like to call this routine", "New Routine");
            int numExercises = Integer.parseInt(JOptionPane.showInputDialog("How many exercises will be in this workout", "Number of Exercises"));
            if (numExercises >=15){
                JOptionPane.showMessageDialog(null, "This is too many exercises(15 Maximum).", "TOO MANY EXERCISES", JOptionPane.WARNING_MESSAGE);
                numExercises = Integer.parseInt(JOptionPane.showInputDialog("How many exercises will be in this workout", "Number of Exercises"));
            }
            String[] exList = new String[numExercises];
            String nameOfRoutine = rName;


                for (int i = 0; i < numExercises; i++){
                    String exerName = JOptionPane.showInputDialog("What is the name of exercise " + (i + 1), "exercise " + (i + 1) + " name");
                    exList[i] = exerName;
                    
                }

                JOptionPane.showMessageDialog(null,"New Workout "+ rName + " Created");
            Routine RoutineName = new Routine(exList, numExercises, rName);


                rList.add(RoutineName);
                System.out.println("routine Created");
    }//GEN-LAST:event_createButtonActionPerformed

    private void viewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewButtonActionPerformed
        // TODO add your handling code here:
         if (rList.isEmpty()) {
             JOptionPane.showMessageDialog(null, "There are no workouts.", "NO WORKOUTS", JOptionPane.WARNING_MESSAGE);
        }else{
             String[] eList = new String[rList.size()];
        for(int j = 0; j < rList.size(); j++){
            eList[j] = rList.get(j).getrName();
        }
        
        
        JComboBox deleter = new JComboBox(eList);
       
        
        //for the jOptionPne
        int input;
        input = JOptionPane.showConfirmDialog(this, deleter, "Select workout to view.",JOptionPane.DEFAULT_OPTION);
        
        
      
        if (input == JOptionPane.OK_OPTION) {
            JOptionPane.showMessageDialog(null, rList.get(input).getexeList());
           
        }
        }    
    }//GEN-LAST:event_viewButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        
        if (rList.isEmpty()) {
             JOptionPane.showMessageDialog(null, "There are no workouts.", "NO WORKOUTS", JOptionPane.WARNING_MESSAGE);
        }else{
        String[] eList = new String[rList.size()];
        for(int j = 0; j < rList.size(); j++){
            eList[j] = rList.get(j).getrName();
        }
        
        
        JComboBox deleter = new JComboBox(eList);
       
        
        //for the jOptionPne
        int input;
        input = JOptionPane.showConfirmDialog(this, deleter, "Select workout to delete.",JOptionPane.DEFAULT_OPTION);
        
        
      
        if (input == JOptionPane.OK_OPTION) {
            
            JOptionPane.showMessageDialog(null, "the Workout " + rList.get(input).getrName() + " has been deleted");
            rList.remove(rList.get(input));
        }
        
        
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        // TODO add your handling code here
        
       
        
        
       
        
        if (rList.isEmpty()) {
             JOptionPane.showMessageDialog(null, "There are no workouts.", "NO WORKOUTS", JOptionPane.WARNING_MESSAGE);
        }else{
        String[] eList = new String[rList.size()];
        for(int j = 0; j < rList.size(); j++){
            eList[j] = rList.get(j).getrName();
        }
        
        
        JComboBox deleter = new JComboBox(eList);
       
        
        //for the jOptionPne
        int input =0;
        
        input = JOptionPane.showConfirmDialog(this, deleter, "Select workout to edit.",JOptionPane.DEFAULT_OPTION);
        universal = input;
        
      
        if (input == JOptionPane.OK_OPTION) {
        EditInterface ei = new EditInterface();
        ei.setSize(800, 600);
        ei.setVisible(true);
        ei.setDefaultCloseOperation(EXIT_ON_CLOSE);
        ei.AAAA.setText(rList.get(input).geteListForEdit()); 
            
            
        }
        
        
        }
        
    }//GEN-LAST:event_editButtonActionPerformed

    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton viewButton;
    // End of variables declaration//GEN-END:variables
}
